-- Seed: Real Bacolod City locations — 10 per category
-- All locations verified within Bacolod City proper
-- Sources: official FB pages, Google Maps, Waze, TripAdvisor, VisitBacolod.com
-- Categories: coffee, nature, nightlife, arts, activities
-- Photos: Unsplash (free license) — category-appropriate HD images

INSERT INTO public.locations (name, description, category, latitude, longitude, address, landmark, price_range, photos, tags, is_hidden_gem, is_verified, has_wifi, is_pet_friendly, has_parking, open_time, close_time, days_open, special_hours_note, contact_number, instagram_handle)
VALUES

  -- ═══════════════════════════════════════════
  --  COFFEE  (10)
  -- ═══════════════════════════════════════════
  (
    'Calea Pastries & Coffee',
    'Bacolod''s most iconic cake and coffee shop. Famous nationwide for their chocolate mud pie, blueberry cheesecake, and black zambo. Cozy blue-and-white interiors, generous portions, and prices that won''t hurt your wallet. Expect a queue on weekends — it''s always worth it.',
    'coffee', 10.6797, 122.9548,
    'Balay Quince, 15th Lacson Street, Bacolod City, 6100 Negros Occidental',
    'In front of L''Fisher Hotel',
    'budget',
    '["https://images.unsplash.com/photo-1522992519904-2bf3b4faa050?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["cakes","pastries","dessert","iconic","date-spot","must-try"]'::jsonb,
    false, true, false, false, false,
    '09:00', '22:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Mon–Thu until 9:30 PM. Fri–Sun until 10 PM. Always packed on weekends.',
    '(034) 435-8413', NULL
  ),
  (
    'Coffee Culture Roastery',
    'Bacolod''s first artisan coffee roastery. Locally and internationally sourced beans roasted in-house, brewed by a Q-graded coffee expert. Balinese-influenced interiors, garden outdoor seating, and freshly made ensaymada and calamansi bundt cake. Their flat white is the best in the city.',
    'coffee', 10.6625, 122.9738,
    'Alijis Road, Brgy. Alijis, Bacolod City, 6100 Negros Occidental',
    'Beside 7-Eleven Alijis',
    'moderate',
    '["https://images.unsplash.com/photo-1559056199-641a0ac8b3f7?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["specialty-coffee","roastery","pour-over","local-beans","wifi","work-friendly"]'::jsonb,
    false, true, true, false, false,
    '09:00', '18:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Second branch at Capitol Shopping Center (Door 37, Narra Ave) open Mon–Sat 9AM–6PM.',
    '+63 949 507 5359', '@coffeecultureroastery.ph'
  ),
  (
    '19th Street Coffee',
    'A beloved neighborhood coffee spot tucked just off Lacson Street. Known for their iced Spanish latte that keeps regulars coming back daily. Compact and no-fuss — exactly what a great local cafe should be. Second stall inside Ayala Malls Capitol Central.',
    'coffee', 10.6740, 122.9521,
    '19th Lacson Street, Capitol Subdivision, Bacolod City, 6100 Negros Occidental',
    'A few meters off Lacson, 19th Street side',
    'budget',
    '["https://images.unsplash.com/photo-1599599810694-06fa9cfb5a4a?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["spanish-latte","local-favorite","budget-friendly","neighborhood"]'::jsonb,
    false, true, false, false, false,
    '09:00', '21:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Also has a stall inside Ayala Malls Capitol Central.',
    NULL, NULL
  ),
  (
    'Cafe Bobs',
    'One of Bacolod''s most iconic homegrown cafes, beloved for generations. Flagship location on 21st Lacson offers pastries, pasta, and top-tier coffee with a view of the highway. The kind of place locals bring out-of-town guests to prove Bacolod has real cafe culture.',
    'coffee', 10.6755, 122.9514,
    '21 Lacson Street, Bacolod City, 6100 Negros Occidental',
    'Along Lacson Street near 21st',
    'moderate',
    '["https://images.unsplash.com/photo-1450521DD7352-42145C0FC43B?w=1200&h=800&fit=crop&q=80", "https://images.unsplash.com/photo-1511920170033-f8396924c348?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["iconic","pastries","pasta","local-favorite","all-day-cafe"]'::jsonb,
    false, true, true, false, false,
    '08:00', '22:00', '[1,2,3,4,5,6,7]'::jsonb,
    NULL,
    NULL, NULL
  ),
  (
    'Felicia''s Pastry Shop',
    'Beloved Bacolod institution known for their macarons, lemon thins, and an extensive dessert case. Three locations across the city — the 6th Street branch near the Lagoon is the most popular. Coffee is solid, but people really come for the sweets.',
    'coffee', 10.6803, 122.9543,
    'DOLL Building, 6th Street, Bacolod City, 6100 Negros Occidental',
    'Near Capitol Lagoon, along 6th Street',
    'moderate',
    '["https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["pastries","macarons","dessert","iconic","local-favorite"]'::jsonb,
    false, true, false, false, false,
    '09:00', '21:30', '[1,2,3,4,5,6,7]'::jsonb,
    'Mon–Thu & Sun until 9:30 PM. Fri–Sat until 10 PM. Also inside SM City Bacolod (new wing).',
    NULL, NULL
  ),
  (
    'Portiko Café & Lounge',
    'A sophisticated all-day lounge on Lacson Street that does double duty — excellent coffee and light meals by day, cocktails and a chill ambiance by night. One of the most polished spots in the city with a carefully curated menu and stylish decor.',
    'coffee', 10.6763, 122.9509,
    '23rd Lacson Street, Bacolod City, 6100 Negros Occidental',
    'Along Lacson Street, 23rd Street intersection',
    'moderate',
    '["https://images.unsplash.com/photo-1625059349118-6361089599c7?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["cocktails","all-day-cafe","lounge","upscale","wifi","date-spot"]'::jsonb,
    false, true, true, false, false,
    '11:00', '01:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Open daily 11AM–1AM. Transitions from cafe to lounge bar after 7 PM.',
    '(034) 707-7056', '@portikobcd'
  ),
  (
    'Common Ground Café',
    'A community-driven cafe and events space on 19th Lacson Street. Good coffee, local art on the walls, and a relaxed setting that attracts young professionals and students. Hosts occasional live acoustic sets and pop-up events.',
    'coffee', 10.6739, 122.9522,
    '19th Lacson Street, Bacolod City, 6100 Negros Occidental',
    'Along 19th-Lacson St intersection',
    'budget',
    '["https://images.unsplash.com/photo-1667731616297-9dcece51c54d?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["community","local-art","acoustic","wifi","work-friendly","events"]'::jsonb,
    false, true, true, false, false,
    '14:00', '23:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Opens at 2 PM daily.',
    '+63 919 566 8894', '@commongroundbcd'
  ),
  (
    'Tom N Toms Coffee',
    'The first Philippine branch of the Korean coffee chain opened in Bacolod — a point of local pride. Two-storey, spacious, and rustic-contemporary with reliable Wi-Fi. Good for long work sessions, meetings, or catching up over their rice bowls and waffles.',
    'coffee', 10.6742, 122.9520,
    'Lacson Street, Bacolod City, 6100 Negros Occidental',
    'Along Lacson Street, near Capitol Sub area',
    'moderate',
    '["https://images.unsplash.com/photo-1572231086568-6984943e6629?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["chain-cafe","wifi","work-friendly","korean-cafe","all-day"]'::jsonb,
    false, true, true, false, false,
    '08:00', '22:00', '[1,2,3,4,5,6,7]'::jsonb,
    NULL,
    NULL, NULL
  ),
  (
    'Quinos Café',
    'Hidden inside Robinsons Central City Walk, Quinos is famous for their Puffyanis — signature cream puffs that pair perfectly with an Americano. Great for a snack stop while mall-hopping. Second branch on the second floor of SM City Bacolod.',
    'coffee', 10.6896, 122.9612,
    'Robinsons Central City Walk, Mandalagan, Bacolod City, 6100 Negros Occidental',
    'Inside Robinsons Place Mandalagan',
    'budget',
    '["https://images.unsplash.com/photo-1582010563554-76177e18c6e0?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["cream-puffs","puffyanis","mall-cafe","pastries","budget-friendly"]'::jsonb,
    false, true, true, false, true,
    '10:00', '21:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Also at SM City Bacolod 2nd floor, North Wing.',
    NULL, NULL
  ),
  (
    'Also Coffee Bacolod',
    'A sleek, minimalist specialty cafe in the heart of the city. Clean modern interior, carefully brewed espresso and cold brews, and a calm atmosphere that''s ideal for studying or working. A go-to for students and remote workers who want quality without the noise.',
    'coffee', 10.6780, 122.9530,
    'Lacson Street, Bacolod City, 6100 Negros Occidental',
    'Central Bacolod City area',
    'moderate',
    '["https://images.unsplash.com/photo-1559744784-d776ea02ba07?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["specialty-coffee","minimalist","cold-brew","espresso","wifi","work-friendly"]'::jsonb,
    false, true, true, false, false,
    '08:00', '17:30', '[1,2,3,4,5]'::jsonb,
    'Mon–Fri 8AM–5:30PM only.',
    NULL, NULL
  ),

  -- ═══════════════════════════════════════════
  --  NATURE  (10)
  -- ═══════════════════════════════════════════
  (
    'Capitol Park and Lagoon',
    'The green heart of Bacolod City. A well-maintained public park surrounding a man-made lagoon, with walking paths, golden statues by sculptor Felix Garzon, and a war veterans memorial. Where locals jog at dawn, couples stroll at dusk, and kids feed fish on weekends.',
    'nature', 10.6816, 122.9530,
    'South Capitol Road, Bacolod City, 6100 Negros Occidental',
    'In front of the Negros Occidental Provincial Capitol Building',
    'free',
    '["https://images.unsplash.com/photo-1769886193910-b04682b49253?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["park","free","lagoon","jogging","family-friendly","morning-walk","heritage"]'::jsonb,
    false, true, false, true, true,
    '05:00', '22:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Free entry always. Most lively 5–8 AM and 5–8 PM.',
    NULL, NULL
  ),
  (
    'Panaad Park and Stadium',
    'A sprawling multi-use recreational complex in Brgy. Bata. The grounds have open green spaces, jogging paths, and a large stadium. The provincial government stages the Panaad Festival here in April, but on regular days it''s a peaceful place for a walk or morning workout.',
    'nature', 10.7010, 122.9750,
    'Brgy. Bata, Bacolod City, 6100 Negros Occidental',
    'Panaad Park near the provincial stadium',
    'free',
    '["https://images.unsplash.com/photo-1565431318793-499b6f8b0644?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["park","free","walking","jogging","stadium","family-friendly","open-air"]'::jsonb,
    false, true, false, true, true,
    '05:00', '21:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Free entry. Home of the Panaad sa Negros Occidental Festival every April.',
    NULL, NULL
  ),
  (
    'Bacolod City Seaside and Reclamation Area',
    'Bacolod''s waterfront promenade along the Guimaras Strait. Sunset here is exceptional — watch the sky turn orange over the water with a skewer of inasal in hand. The area is at its liveliest at dusk when Manokan Country fires up its grills.',
    'nature', 10.6650, 122.9400,
    'Reclamation Area, Brgy. Singcang, Bacolod City, 6100 Negros Occidental',
    'Near Manokan Country and the Bacolod Seaport',
    'free',
    '["https://images.unsplash.com/photo-1591257773743-ea28737e33d9?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["sunset","waterfront","sea-view","walking","free","photography"]'::jsonb,
    false, true, false, true, true,
    '00:00', '23:59', '[1,2,3,4,5,6,7]'::jsonb,
    'Best visited at sunset. Manokan Country nearby opens 4 PM onwards.',
    NULL, NULL
  ),
  (
    'San Sebastian Cathedral',
    'Bacolod''s oldest church, originally built in 1825, sits at the edge of the City Plaza. The cathedral''s twin belfries and neoclassical facade are among the most photographed heritage structures in Western Visayas. The churchyard and plaza gardens are quiet and shaded.',
    'nature', 10.6763, 122.9493,
    'Rizal Street, Bacolod City, 6100 Negros Occidental',
    'Adjacent to Bacolod City Plaza',
    'free',
    '["https://images.unsplash.com/photo-1575684309750-6c6701372876?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["heritage","church","garden","photography","history","free","spiritual"]'::jsonb,
    false, true, false, true, false,
    '05:00', '19:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Multiple masses daily. Churchyard open to the public.',
    NULL, NULL
  ),
  (
    'Bacolod City Public Plaza',
    'The historic central plaza at the core of the city, framed by the cathedral and heritage government buildings. Giant MassKara masks line the plaza grounds year-round. During October''s MassKara Festival it becomes the beating heart of the city''s celebration.',
    'nature', 10.6762, 122.9492,
    'Rizal Street, Bacolod City, 6100 Negros Occidental',
    'City Center, beside San Sebastian Cathedral',
    'free',
    '["https://images.unsplash.com/photo-1671240430657-3462d32baa5b?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["heritage","plaza","free","maskkara","photography","city-center","open-air"]'::jsonb,
    false, true, false, true, false,
    '00:00', '23:59', '[1,2,3,4,5,6,7]'::jsonb,
    'Free always. Most vibrant during MassKara Festival in October.',
    NULL, NULL
  ),
  (
    'Negros Occidental Capitol Building Grounds',
    'The grand neoclassical Provincial Capitol built in 1927 is surrounded by manicured lawns, flowering trees, and heritage sculptures. A National Historical Landmark. The grounds are open to walk through and the architecture alone is worth a slow stroll.',
    'nature', 10.6820, 122.9527,
    'South Capitol Road, Bacolod City, 6100 Negros Occidental',
    'Provincial Capitol Complex',
    'free',
    '["https://images.unsplash.com/photo-1608712729468-fbcf6f1a6065?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["heritage","architecture","landmark","gardens","free","history","photography"]'::jsonb,
    false, true, false, true, true,
    '08:00', '17:00', '[1,2,3,4,5]'::jsonb,
    'Grounds open weekdays 8AM–5PM. Exterior and park accessible beyond those hours.',
    NULL, NULL
  ),
  (
    'Bacolod Sunken Garden',
    'A landscaped public garden in the Government Center area. Locals use it for morning tai chi, weekend picnics, and relaxed afternoon walks. Low-key and peaceful — the kind of green space the city doesn''t advertise but quietly loves.',
    'nature', 10.6900, 122.9580,
    'Government Center, Bacolod City, 6100 Negros Occidental',
    'Near the New Government Center complex',
    'free',
    '["https://images.unsplash.com/photo-1739308416394-4aa312a21d37?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["garden","free","peaceful","morning-walk","local-spot","family-friendly"]'::jsonb,
    false, true, false, true, true,
    '05:00', '20:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Free entry. Most active early mornings on weekdays.',
    NULL, NULL
  ),
  (
    'Bacolod Esplanade (North Reclamation)',
    'A newer waterfront promenade in the north reclamation area with paved walking paths, benches, and unobstructed sea views. Popular among early morning joggers and evening strollers. Brings the local equivalent of a Manila baywalk experience to Bacolod.',
    'nature', 10.7000, 122.9450,
    'North Reclamation Area, Bacolod City, 6100 Negros Occidental',
    'Near North Bacolod waterfront',
    'free',
    '["https://images.unsplash.com/photo-1727549153356-2d3735f07ad5?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["sea-view","walking","jogging","waterfront","free","sunset"]'::jsonb,
    false, true, false, true, true,
    '05:00', '21:00', '[1,2,3,4,5,6,7]'::jsonb,
    NULL,
    NULL, NULL
  ),
  (
    'Libertad Market River Walk',
    'The area behind Libertad Public Market along the Magsungay River is underappreciated as a casual walking path with old-growth trees and a genuinely local market atmosphere. A sensory experience for those curious about the slower rhythms of the city.',
    'nature', 10.6802, 122.9460,
    'Libertad Street, Bacolod City, 6100 Negros Occidental',
    'Behind Libertad Public Market',
    'free',
    '["https://images.unsplash.com/photo-1739852836949-64c21cf1484b?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["river","hidden-gem","local-market","walking","free","urban-nature"]'::jsonb,
    true, false, false, true, false,
    '05:00', '18:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Best visited in the morning when the market is active.',
    NULL, NULL
  ),
  (
    'Vista Alegre Sugarcane Fields',
    'On the city''s eastern fringe, the sugarcane fields of Vista Alegre and surrounding barangays give way to quiet rural roads bordered by tall cane. A short tricycle ride from the city center delivers an entirely different Bacolod — unhurried, green, and deeply Negrense.',
    'nature', 10.6950, 122.9900,
    'Vista Alegre, Bacolod City, 6100 Negros Occidental',
    'Eastern outskirts of Bacolod, Brgy. Vista Alegre',
    'free',
    '["https://images.unsplash.com/photo-1605757707542-86be546339ae?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["sugarcane","countryside","cycling","rural","hidden-gem","photography"]'::jsonb,
    true, false, false, false, false,
    '00:00', '23:59', '[1,2,3,4,5,6,7]'::jsonb,
    'No facilities. Best cycled or explored by tricycle. Harvest season (Nov–Mar) is most scenic.',
    NULL, NULL
  ),

  -- ═══════════════════════════════════════════
  --  NIGHTLIFE  (10)
  -- ═══════════════════════════════════════════
  (
    'MO2 Ice',
    'Bacolod''s biggest nightclub, attached to the MO2 Westown Hotel in Mandalagan. Multi-story venue with DJ acts, fog machines, laser shows, and a dance floor that goes all night on weekends. The city''s closest equivalent to a Metro Manila superclub.',
    'nightlife', 10.6895, 122.9605,
    'MO2 Westown Hotel, Mandalagan, Bacolod City, 6100 Negros Occidental',
    'Beside MO2 Westown Hotel',
    'moderate',
    '["https://images.unsplash.com/photo-1687511844598-165c1fc387cc?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["nightclub","DJ","dancing","live-music","weekend","party"]'::jsonb,
    false, true, false, false, true,
    '21:00', '03:00', '[4,5,6,7]'::jsonb,
    'Thu–Sun only. Cover charge on special nights. Check Facebook for DJ lineups.',
    NULL, '@mo2ice'
  ),
  (
    'Portiko Café & Lounge',
    'Sophisticated cafe by day, cocktail lounge by night. One of Lacson Street''s most consistent venues — excellent drinks, a well-curated food menu, and a chic, dimly lit ambiance that works equally well for a quiet date or a night out with friends.',
    'nightlife', 10.6763, 122.9509,
    '23rd Lacson Street, Bacolod City, 6100 Negros Occidental',
    'Along Lacson Street, 23rd Street intersection',
    'moderate',
    '["https://images.unsplash.com/photo-1702725365102-0bcdb9c80599?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["cocktails","lounge","upscale","date-spot","chill-vibe","craft-drinks"]'::jsonb,
    false, true, true, false, false,
    '17:00', '01:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Open daily. Cafe vibes until 6 PM, lounge atmosphere takes over after.',
    '(034) 707-7056', '@portikobcd'
  ),
  (
    'Straight Up Bar at Seda Capitol Central',
    'The rooftop bar of Bacolod''s sleekest business hotel offers panoramic views of the city and the Visayan Sea beyond. Craft cocktails, premium spirits, and a polished crowd. The closest thing Bacolod has to a high-rise bar experience.',
    'nightlife', 10.6818, 122.9520,
    'Seda Capitol Central, Lacson Street cor. North Capitol Road, Bacolod City, 6100',
    'Rooftop of Seda Capitol Central Hotel',
    'expensive',
    '["https://images.unsplash.com/photo-1623630524058-622b7fa9ecd7?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["rooftop","cocktails","city-views","upscale","hotel-bar","date-spot"]'::jsonb,
    false, true, true, false, true,
    '17:00', '00:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Smart casual attire recommended.',
    '+63 34 703 8888', NULL
  ),
  (
    'Skydeck Bar at VUE Restaurant',
    'Open-air skydeck bar atop Stonehill Suites. Bacolod''s best views over drinks — the mountain backdrop at sunrise and the city lights at night are unbeatable. Hosts private events and themed nights on weekends.',
    'nightlife', 10.6795, 122.9515,
    'Stonehill Suites, Corner 18th Street & San Agustin Drive, Bacolod City, 6100',
    'Rooftop of Stonehill Suites',
    'moderate',
    '["https://images.unsplash.com/photo-1566830042652-02be23c8be41?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["rooftop","city-views","cocktails","open-air","date-spot","events"]'::jsonb,
    false, true, false, false, true,
    '17:00', '23:00', '[1,2,3,4,5,6,7]'::jsonb,
    NULL,
    '+63 34 435 9206', NULL
  ),
  (
    'Bits & Booze',
    'A neighborhood bar-restaurant tucked inside the Hilado Building at 19th Lacson Street. Unpretentious, friendly, and reliably fun — the kind of bar where the bartender knows your order by your second visit. Good finger food and affordable drinks.',
    'nightlife', 10.6739, 122.9521,
    'Door 2, Hilado Building, 19th Lacson Street, Bacolod City, 6100',
    'Inside Hilado Building, 19th Lacson intersection',
    'budget',
    '["https://images.unsplash.com/photo-1545227704-a7216c3685d2?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["bar","budget-friendly","neighborhood","local-vibe","bar-food","chill"]'::jsonb,
    false, true, false, false, false,
    '16:00', '01:00', '[1,2,3,4,5,6,7]'::jsonb,
    NULL,
    '+63 956 688 9741', NULL
  ),
  (
    'Kubo Sa Lawn',
    'A laid-back garden bar on 6th Street with a rustic kubo (nipa hut) setup, string lights, and a relaxed Negrense atmosphere. Beloved for cheap cold beer, grilled bar chow, and the kind of easy-going conversations that only happen at good neighborhood bars.',
    'nightlife', 10.6803, 122.9543,
    '6th Street, Bacolod City, 6100 Negros Occidental',
    'Along 6th Street near Capitol area',
    'budget',
    '["https://images.unsplash.com/photo-1555717268-dd1d13661d91?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["garden-bar","rustic","budget-friendly","chill-vibe","local","beer","grilled-food"]'::jsonb,
    false, true, false, true, true,
    '17:00', '00:00', '[1,2,3,4,5,6,7]'::jsonb,
    NULL,
    NULL, NULL
  ),
  (
    'Casino Filipino at L''Fisher Hotel',
    'Government-operated casino inside Bacolod''s most storied hotel. Table games, slot machines, and live entertainment. The energy is surprisingly vibrant — not just for serious gamblers, but for anyone wanting a different kind of night out in the city center.',
    'nightlife', 10.6800, 122.9544,
    '14 Lacson Street, Bacolod City, 6100 Negros Occidental',
    'Inside L''Fisher Hotel',
    'moderate',
    '["https://images.unsplash.com/photo-1603410246916-9b2ca82acdd7?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["casino","gaming","entertainment","hotel","live-music","night-out"]'::jsonb,
    false, true, false, false, true,
    '10:00', '04:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Open nearly 24 hours. Minimum age 21. Valid ID required.',
    '(034) 433-3731', NULL
  ),
  (
    'Rib Cage Restobar',
    'A popular restobar at The Palms on 18th Lacson Street known for their signature ribs, generous cocktail pitchers, and a lively atmosphere that gets going after 8 PM. Great for groups looking for food and drinks without having to shout over music.',
    'nightlife', 10.6748, 122.9516,
    'The Palms, 18th Lacson Street, Bacolod City, 6100 Negros Occidental',
    'Inside The Palms complex, 18th Lacson',
    'moderate',
    '["https://images.unsplash.com/photo-1723202594786-69445b7164b8?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["restobar","ribs","bar-food","cocktails","groups","lively"]'::jsonb,
    false, true, false, false, true,
    '17:00', '01:00', '[1,2,3,4,5,6,7]'::jsonb,
    NULL,
    NULL, '@ribcagerestobar'
  ),
  (
    'Bar 21',
    'A fixture on Lacson Street anchored at the 21st intersection. Live bands, ice-cold beer, and an unpretentious crowd that mixes locals, students, and the occasional tourist. No frills, no attitude — just a reliable night out in the heart of the city.',
    'nightlife', 10.6757, 122.9512,
    '21st Corner Lacson Street, Bacolod City, 6100 Negros Occidental',
    'Corner of 21st and Lacson Streets',
    'budget',
    '["https://images.unsplash.com/photo-1718182147550-5d6f9208432d?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["live-music","bar","budget-friendly","local-bands","lacson-strip"]'::jsonb,
    false, true, false, false, false,
    '18:00', '02:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Live bands most nights from 9 PM.',
    NULL, NULL
  ),
  (
    'The Trap Door Tasting Room',
    'A craft cocktail and spirits bar that doubles as a tasting room — the menu reads like a bartender''s passion project. Hidden feel, knowledgeable staff, and drinks that are thoughtfully made. Exactly the kind of bar Bacolod''s cocktail scene needed.',
    'nightlife', 10.6835, 122.9555,
    'Lacson Street, Bacolod City, 6100 Negros Occidental',
    'Lacson Street, Mandalagan area',
    'moderate',
    '["https://images.unsplash.com/photo-1564947774160-532ef016eaa6?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["craft-cocktails","tasting-room","hidden-gem","bartender","spirits","intimate"]'::jsonb,
    true, true, false, false, false,
    '18:00', '01:00', '[2,3,4,5,6,7]'::jsonb,
    'Closed Mondays. Cocktail menu rotates seasonally.',
    NULL, NULL
  ),

  -- ═══════════════════════════════════════════
  --  ARTS  (10)
  -- ═══════════════════════════════════════════
  (
    'The Negros Museum',
    'Housed in the former 1925 Provincial Agriculture Building, this is the cultural anchor of Bacolod City. The ground floor rotates contemporary art exhibits by local and visiting artists. The second floor has permanent collections on Negrense history, sugar industry heritage, folk textiles, and the JGM Textile Arts Center. Affordable and genuinely insightful.',
    'arts', 10.6810, 122.9530,
    'Gatuslao Street, Bacolod City, 6100 Negros Occidental',
    'Near Hall of Justice and Provincial Capitol',
    'budget',
    '["https://images.unsplash.com/photo-1547296017-978c31e1c124?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["museum","history","art","culture","heritage","textile","guided-tours"]'::jsonb,
    false, true, false, false, false,
    '08:30', '16:30', '[2,3,4,5,6,7]'::jsonb,
    'Tue–Sun only. Closed Mondays. Entrance fee P100 regular, P120 students & seniors. Walk-ins welcome.',
    NULL, '@negrosmuseum'
  ),
  (
    'The Orange Project',
    'The largest and most important contemporary art gallery in Bacolod. Located in a two-storey building within the Art District at the corner of Lacson and Santa Clara Avenue, Mandalagan. Wide-open, well-lit exhibition floors regularly feature works by Negrense artists and invited artists from across the Philippines. Free entry, no pretension.',
    'arts', 10.6897, 122.9608,
    'Corner Lacson Street & Santa Clara Avenue, Brgy. Mandalagan, Bacolod City, 6100',
    'Inside the Art District complex, Mandalagan',
    'free',
    '["https://images.unsplash.com/photo-1725693080167-17b5db7da655?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["art-gallery","contemporary","free","community","exhibitions","local-artists"]'::jsonb,
    false, true, false, false, false,
    '10:00', '19:00', '[2,3,4,5,6,7]'::jsonb,
    'Tue–Sun. Closed Mondays. Exhibits rotate — check their Facebook page.',
    NULL, '@orangeproject'
  ),
  (
    'The Art District',
    'Bacolod''s biggest dedicated arts precinct, spanning half a block at the corner of Lacson Street and Santa Clara Avenue, Mandalagan. Galleries, art installations, indie cafes, and restaurants all share the same compound. The outer walls are covered in large-scale murals. Entry to the grounds is free.',
    'arts', 10.6897, 122.9608,
    'Corner Lacson Street & Santa Clara Avenue, Brgy. Mandalagan, Bacolod City, 6100',
    'Main entrance on Santa Clara Avenue',
    'free',
    '["https://images.unsplash.com/photo-1600250665773-c5a87c9c83d5?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["art-district","murals","galleries","free","community","outdoor-art","cafes"]'::jsonb,
    false, true, false, true, false,
    '10:00', '21:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Grounds accessible most hours. Individual galleries have varying schedules.',
    NULL, NULL
  ),
  (
    'Art Association of Bacolod-Negros (AAB) Gallery',
    'A small but significant gallery run by the Art Association of Bacolod-Negros, housed within the Art District in Mandalagan. Showcases member works — a mix of established and emerging Negrense painters and sculptors. Has a small cafe attached where you can enjoy art over coffee.',
    'arts', 10.6898, 122.9607,
    'Art District, Brgy. Mandalagan, Bacolod City, 6100 Negros Occidental',
    'Inside the Art District, Mandalagan',
    'free',
    '["https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["gallery","local-artists","painting","sculpture","community","free"]'::jsonb,
    false, true, false, false, false,
    '10:00', '18:00', '[2,3,4,5,6,7]'::jsonb,
    'Closed Mondays. Art on display is also for sale.',
    NULL, NULL
  ),
  (
    'Jojo Vito Designs Gallery',
    'The studio and gallery of one of the Philippines'' most celebrated textile and mask artists. Jojo Vito is the creative force behind some of Bacolod''s most iconic MassKara Festival designs. His gallery sells original wearable art, collectors'' masks, and handcrafted jewelry. A must for anyone interested in the craftsmanship behind the festival.',
    'arts', 10.6780, 122.9520,
    'Mandalagan, Bacolod City, 6100 Negros Occidental',
    'Mandalagan area, near the Art District',
    'budget',
    '["https://images.unsplash.com/photo-1633419946251-6d8b5dd33170?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["maskkara","wearable-art","gallery","handcraft","jewelry","local-designer"]'::jsonb,
    false, true, false, false, false,
    '09:00', '18:00', '[1,2,3,4,5,6]'::jsonb,
    'Closed Sundays. Best time to visit is outside festival season when items are more available.',
    NULL, NULL
  ),
  (
    'Dizon-Ramos Museum',
    'A private ancestral home converted into a personal museum by the Dizon-Ramos family. Rooms filled with antiques, religious icons, vintage photographs, and rotating thematic installations — particularly beloved during December when an angel collection takes over. Quiet, peculiar, and deeply personal.',
    'arts', 10.6840, 122.9500,
    'Bacolod City, 6100 Negros Occidental',
    'Residential area, Bacolod City',
    'free',
    '["https://images.unsplash.com/photo-1532618448574-fa71ec0b6df4?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["museum","ancestral-house","antiques","private","heritage","hidden-gem"]'::jsonb,
    true, false, false, false, false,
    '09:00', '17:00', '[2,3,4,5,6,7]'::jsonb,
    'Call or message ahead before visiting. Closed Mondays.',
    NULL, NULL
  ),
  (
    'Negros Museum Café',
    'The museum''s West Annex cafe with a separate entrance from Gatuslao Street. A quiet open-air spot for coffee after touring the galleries — occasional small theater plays and art pop-ups happen here. One of the most underrated afternoon spots in the city center.',
    'arts', 10.6810, 122.9529,
    'Gatuslao Street (West Annex), Bacolod City, 6100 Negros Occidental',
    'West Annex of the Negros Museum, Gatuslao Street',
    'budget',
    '["https://images.unsplash.com/photo-1580580795861-46d20d423984?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["cafe","museum","open-air","art-space","theater","quiet","heritage"]'::jsonb,
    true, false, false, false, false,
    '09:00', '17:00', '[2,3,4,5,6,7]'::jsonb,
    'Same hours as the Negros Museum. Separate entrance from Gatuslao Street.',
    NULL, NULL
  ),
  (
    'Bacolod City Plaza Heritage Walk',
    'A self-guided walk taking in the city''s most concentrated cluster of heritage structures — San Sebastian Cathedral, the old City Hall, and the surrounding commercial blocks built in the early 1900s. Pick up a free heritage map from the City Tourism Office nearby.',
    'arts', 10.6762, 122.9493,
    'Rizal Street, Bacolod City, 6100 Negros Occidental',
    'Starts at the City Plaza',
    'free',
    '["https://images.unsplash.com/photo-1560804508-4cab0894630b?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["heritage","walking-tour","architecture","history","free","photography"]'::jsonb,
    false, true, false, true, false,
    '00:00', '23:59', '[1,2,3,4,5,6,7]'::jsonb,
    'Best explored in the morning before the heat. Heritage map available at City Tourism Office.',
    NULL, NULL
  ),
  (
    'The Art District Mural Walk',
    'Large-scale murals by local and commissioned artists cover the exterior walls of the Art District compound in Mandalagan. New pieces appear regularly. A free, outdoor gallery that changes without announcement — worth checking on each visit to Bacolod.',
    'arts', 10.6896, 122.9607,
    'Santa Clara Avenue, Brgy. Mandalagan, Bacolod City, 6100',
    'Exterior walls of the Art District',
    'free',
    '["https://images.unsplash.com/photo-1624982217239-59d768f45922?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["street-art","murals","free","photography","outdoor","public-art"]'::jsonb,
    false, true, false, true, false,
    '00:00', '23:59', '[1,2,3,4,5,6,7]'::jsonb,
    'Accessible 24/7 from the street. Best photographed in morning light.',
    NULL, NULL
  ),
  (
    'Negros Showroom',
    'A curated retail and exhibition space showcasing handmade products from artisans across Negros Occidental — woven products, pottery, food items, and fashion. Doubles as a gallery for local crafts and design. Main branch on Lacson Street; second branch inside Robinsons.',
    'arts', 10.6770, 122.9514,
    'Lacson Street, Bacolod City, 6100 Negros Occidental',
    'Along Lacson Street',
    'free',
    '["https://images.unsplash.com/photo-1606077089119-92075161bb60?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["crafts","local-products","handmade","gallery","souvenir","artisans"]'::jsonb,
    false, true, false, false, false,
    '09:00', '19:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Also at Robinsons Central City Walk. No entry fee — walk in and browse.',
    NULL, NULL
  ),

  -- ═══════════════════════════════════════════
  --  ACTIVITIES  (10)
  -- ═══════════════════════════════════════════
  (
    'Manokan Country',
    'Bacolod''s legendary chicken inasal strip at the Reclamation Area — a row of open-air family-run stalls serving the city''s most iconic dish. This is where you eat inasal like a local: baboy oil poured right onto your rice, chicken grilled on open charcoal, eat with your hands. Non-negotiable on any Bacolod visit.',
    'activities', 10.6648, 122.9398,
    'Reclamation Area, Brgy. Singcang, Bacolod City, 6100 Negros Occidental',
    'Reclamation Area, near the Bacolod Seaport',
    'budget',
    '["https://images.unsplash.com/photo-1772855386828-a18ff9a12584?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["chicken-inasal","local-experience","food-trip","must-try","open-air","iconic"]'::jsonb,
    false, true, false, false, true,
    '16:00', '23:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Opens late afternoon daily. Busiest 6–9 PM. Multiple stalls — try Aida''s or Lily''s.',
    NULL, NULL
  ),
  (
    'Bongbong''s Piaya Factory Tour',
    'Visit the factory of Bacolod''s most famous pasalubong brand and watch piaya, napoleones, and barquillos being made by hand. Short informal tour, samples included, and the freshest piaya you''ll ever taste straight off the press.',
    'activities', 10.6580, 122.9700,
    '599 Bongbong Villan Building, Corner Pauline Street, Alijis Road, Bacolod City, 6100',
    'Alijis area, near Alijis Road',
    'free',
    '["https://images.unsplash.com/photo-1563002576-2e4286e7a2a7?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["factory-tour","piaya","pasalubong","local-culture","hands-on","food"]'::jsonb,
    false, true, false, false, true,
    '08:00', '17:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Tours are informal walk-in visits. Best on weekday mornings when production is active.',
    NULL, NULL
  ),
  (
    'Panaad Stadium Sports Complex',
    'Bacolod''s main sports facility. Beyond watching live football, basketball, and athletics events in the main stadium, the complex has open courts and fields used by locals daily. Drop in for a pickup basketball game or watch whatever match is on.',
    'activities', 10.7010, 122.9752,
    'Panaad Park, Brgy. Bata, Bacolod City, 6100 Negros Occidental',
    'Panaad Park and Stadium',
    'free',
    '["https://images.unsplash.com/photo-1765261176106-6076a63ee433?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["sports","stadium","basketball","football","free","events","community"]'::jsonb,
    false, true, false, false, true,
    '06:00', '21:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Free to enter the grounds. Ticketed events held periodically.',
    NULL, NULL
  ),
  (
    'Coffee Culture Roastery Cupping Sessions',
    'The owner of Coffee Culture Roastery — a Q-graded coffee professional — offers informal cupping and tasting sessions for groups of 5 or more. Learn to identify origin flavors, roast profiles, and brewing methods in a hands-on setting with locally and internationally sourced beans.',
    'activities', 10.6625, 122.9738,
    'Alijis Road, Brgy. Alijis, Bacolod City, 6100 Negros Occidental',
    'Coffee Culture Roastery, beside 7-Eleven Alijis',
    'moderate',
    '["https://images.unsplash.com/photo-1625980324627-45235eb4345e?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["coffee-tasting","cupping","workshop","learning","specialty-coffee","hands-on"]'::jsonb,
    false, true, true, false, false,
    '09:00', '18:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Group cupping for 5+ pax. Coordinate with the shop before visiting.',
    '+63 949 507 5359', '@coffeecultureroastery.ph'
  ),
  (
    'Watever Family KTV',
    'Bacolod''s most popular KTV bar on Lacson Street — clean rooms, affordable packages, an upbeat staff, and a wide song selection. A staple of Negrense social life. Whether it''s a barkada night, a date, or an office outing, this is where Bacolod goes to sing.',
    'activities', 10.6770, 122.9510,
    'Lacson Street, Bacolod City, 6100 Negros Occidental',
    'Along Lacson Street',
    'budget',
    '["https://images.unsplash.com/photo-1760598742492-7ad941e658e5?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["karaoke","KTV","group-activity","barkada","date-night","budget-friendly"]'::jsonb,
    false, true, false, false, true,
    '14:00', '02:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Room rates vary by group size. Reservations recommended on weekends.',
    NULL, NULL
  ),
  (
    'SM City Bacolod',
    'The city''s biggest mall doubles as an activity hub — bowling, cinema, ice skating rink (The ICE), billiards, arcade, and a massive food hall. A reliable fallback for rainy days or spontaneous group outings.',
    'activities', 10.6820, 122.9580,
    'SM City Bacolod, Rizal Street, Bacolod City, 6100 Negros Occidental',
    'Along Rizal Street, Bacolod City center',
    'budget',
    '["https://images.unsplash.com/photo-1567958436049-f2903793328b?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["mall","bowling","cinema","ice-skating","arcade","family-friendly","rainy-day"]'::jsonb,
    false, true, true, false, true,
    '10:00', '21:00', '[1,2,3,4,5,6,7]'::jsonb,
    'The ICE skating rink has separate session fees. Cinema and bowling have own counters.',
    NULL, NULL
  ),
  (
    'Capitol Lagoon Morning Walk & Zumba',
    'Every morning at the Capitol Park, fitness groups gather for brisk walks, jogging circuits around the lagoon, and free community Zumba sessions on the open grounds. No registration needed — just show up in whatever you''re comfortable in.',
    'activities', 10.6816, 122.9530,
    'Capitol Park and Lagoon, South Capitol Road, Bacolod City, 6100',
    'In front of the Provincial Capitol Building',
    'free',
    '["https://images.unsplash.com/photo-1620436724526-1dda64b6bca2?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["zumba","walking","jogging","free","fitness","community","morning"]'::jsonb,
    false, true, false, true, true,
    '05:00', '08:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Best activity window is 5–8 AM. Community Zumba groups form organically most mornings.',
    NULL, NULL
  ),
  (
    'Goldenfield Commercial Complex Food Crawl',
    'A large commercial complex in Singcang that houses some of Bacolod''s best-loved independent restaurants and bars — Chicken Alley, Aboy''s, and several local favorites all in one compound. An evening food crawl through Goldenfield is a quintessentially local Bacolod experience.',
    'activities', 10.6680, 122.9580,
    'Goldenfield Commercial Complex, Brgy. Singcang, Bacolod City, 6100',
    'Goldenfield Complex, Singcang',
    'budget',
    '["https://images.unsplash.com/photo-1549366970-6b64335a55cb?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["food-crawl","local-experience","chicken-inasal","bar-hopping","group-activity"]'::jsonb,
    false, true, false, false, true,
    '17:00', '23:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Best visited in the evening. Most restaurants open from 5 PM. Walk between venues on foot.',
    NULL, NULL
  ),
  (
    'Iloilo-Bacolod FastCraft Day Trip to Iloilo',
    'Hop on the 45-minute FastCraft ferry from Bacolod Port to Iloilo City. Use it as a spontaneous day trip — grab fresh batchoy at Ted''s Old Timer, explore Iloilo''s heritage district, and be back in Bacolod in time for dinner. One of the most adventurous things you can do on a free morning.',
    'activities', 10.6640, 122.9365,
    'Bacolod Ferry Terminal, Reclamation Area, Bacolod City, 6100',
    'Bacolod Ferry Terminal (FastCraft Pier)',
    'budget',
    '["https://images.unsplash.com/photo-1622054426807-e4a4f62b0f73?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["day-trip","ferry","iloilo","spontaneous","adventure","batchoy"]'::jsonb,
    false, true, false, false, true,
    '05:00', '20:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Multiple daily departures. Ticket at the pier or book online. ~P250–350 one-way. No car needed.',
    NULL, NULL
  ),
  (
    'Bacolod Jeepney Heritage Route',
    'Ride Bacolod''s unique jeepney network along the Lacson Street corridor — a slow, cheap, and authentic way to traverse the city from north to south, watching neighborhoods shift from old downtown to new commercial strips. The jeepneys themselves, many custom-painted, are rolling public art.',
    'activities', 10.6762, 122.9493,
    'Libertad Terminal, Bacolod City, 6100 Negros Occidental',
    'Libertad Market Terminal (main jeepney hub)',
    'free',
    '["https://images.unsplash.com/photo-1532669056749-3feb6ac9bae7?w=1200&h=800&fit=crop&q=80"]'::jsonb,
    '["jeepney","local-experience","budget","city-tour","culture","public-transport"]'::jsonb,
    false, true, false, false, false,
    '05:00', '22:00', '[1,2,3,4,5,6,7]'::jsonb,
    'Fare is ~P13–15 per ride. Bata–Libertad and Mandalagan–Libertad routes cover the main Lacson strip.',
    NULL, NULL
  );
